FROM golang:1.26.4

WORKDIR /app

# Ferramentas úteis para desenvolvimento
RUN go install github.com/air-verse/air@latest

COPY app/go.mod app/go.sum ./

RUN go mod download

EXPOSE 8080

CMD ["tail", "-f", "/dev/null"]