version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pg_rabbitmq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - ssl=off
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      enviroment:
        rabbitmq_username: ${rabbitmq_username}
        rabbitmq_password: ${rabbitmq_password}
        rabbitmq_host: ${rabbitmq_host}
        rabbitmq_port: ${rabbitmq_port}
        postgres_host: ${postgres_host}
        postgres_port: ${postgres_port}
        postgres_db: ${postgres_db}
        postgres_user: ${postgres_user}
        postgres_password: ${postgres_password}
    container_name: app

    working_dir: /app

    env_file:
      - development.env

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    volumes:
      - ./app:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
  go-build-cache:
  postgres_data:
  rabbitmq_data: